const key=id=>`tofuctf:${id}`,isSolved=id=>localStorage.getItem(key(id))==='solved';
const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());
let items=[],active=null,view=new Date(`${today}T12:00:00+09:00`);
const card=(c,compact=false)=>`<article class="challenge ${isSolved(c.id)?'solved':''} ${compact?'compact':''}" id="${compact?'archive-':''}${c.id}"><div class="challenge-main"><div class="tags"><span>PWN</span><span>${compact?c.topic.toUpperCase():'BEGINNER +1'}</span><span>${c.points} PTS</span></div><h3>${c.title}</h3><p>${c.subtitle}</p><dl><div><dt>ARCH</dt><dd>${c.arch}</dd></div><div><dt>MITIGATIONS</dt><dd>${c.mitigations}</dd></div><div><dt>ACCESS</dt><dd>localhost:${c.port}</dd></div></dl></div><aside class="challenge-side"><div class="difficulty"><span>DIFFICULTY</span><b>${'●'.repeat(c.level)}${'○'.repeat(5-c.level)}</b></div><a class="download" href="${c.download}" download>${compact?'Download':'Download challenge'} <span>↓</span></a><button class="open-modal" data-id="${c.id}" type="button">${isSolved(c.id)?'Solved ✓':'Submit flag'}</button><small class="solve-state">${isSolved(c.id)?'✓ Solved locally':'Not solved yet'}</small></aside></article>`;
function bind(){document.querySelectorAll('.open-modal').forEach(b=>b.onclick=()=>{active=items.find(c=>c.id===b.dataset.id);dialogKicker.textContent=`CHALLENGE ${String(active.number).padStart(3,'0')}`;dialogTitle.textContent=active.title;flagInput.value='';flagMessage.textContent='';flagDialog.showModal()})}
function render(){const available=items.filter(c=>c.date<=today),latest=available.find(c=>c.date===today)||available.at(-1),filter=challengeFilter.value;todayChallenge.innerHTML=latest?card(latest):'<p>最初の問題を準備中。</p>';challengeList.innerHTML=available.filter(c=>c!==latest).filter(c=>filter==='all'||(filter==='solved')===isSolved(c.id)).reverse().map(c=>card(c,true)).join('');solvedCount.textContent=available.filter(c=>isSolved(c.id)).length;availableCount.textContent=String(available.length).padStart(2,'0');comebackCount.textContent=localStorage.getItem('tofuctf:comebacks')||0;bind();renderCalendar()}
function renderCalendar(){const y=view.getFullYear(),m=view.getMonth(),offset=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),cells=Array(offset).fill('<span class="calendar-day blank"></span>');monthLabel.textContent=`${y}.${String(m+1).padStart(2,'0')}`;for(let d=1;d<=days;d++){const date=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,c=items.find(x=>x.date===date),kind=c?(isSolved(c.id)?'solved':date<=today?'available':'rest'):'rest';cells.push(`<button class="calendar-day ${kind}" ${c&&date<=today?`data-jump="${c.id}"`:'disabled'}><b>${d}</b>${c?`<small>#${String(c.number).padStart(2,'0')}</small>`:''}</button>`)}calendarGrid.innerHTML=cells.join('');document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.querySelector(`#${b.dataset.jump}`)?.scrollIntoView({behavior:'smooth',block:'center'}))}
submitFlag.onclick=()=>{if(/^TofuCTF\{[a-f0-9]{32}\}$/.test(flagInput.value.trim())&&active){localStorage.setItem(key(active.id),'solved');flagMessage.textContent='Correct format — tofu secured!';flagMessage.style.color='#1f5b45';render();setTimeout(()=>flagDialog.close(),700)}else{flagMessage.textContent='形式が違うようです。exploitの出力を確認しよう。';flagMessage.style.color='#a23b31'}};
focusButton.onclick=()=>focusDialog.showModal();challengeFilter.onchange=render;prevMonth.onclick=()=>{view.setMonth(view.getMonth()-1);renderCalendar()};nextMonth.onclick=()=>{view.setMonth(view.getMonth()+1);renderCalendar()};pickBacklog.onclick=()=>{const backlog=items.filter(c=>c.date<=today&&!isSolved(c.id)),pick=backlog[Math.floor(Math.random()*backlog.length)];if(pick){localStorage.setItem('tofuctf:comebacks',String(Number(localStorage.getItem('tofuctf:comebacks')||0)+1));document.querySelector(`#${pick.id}`)?.scrollIntoView({behavior:'smooth',block:'center'});render()}};
fetch('challenges.json').then(r=>r.json()).then(data=>{items=data.sort((a,b)=>a.date.localeCompare(b.date));render()}).catch(()=>todayChallenge.textContent='問題一覧を読み込めませんでした。');
